# Generated by Django 6.0.2 on 2026-03-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unitoutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentItem1', models.CharField(max_length=40)),
                ('AssessmentItem1DueDate', models.DateField()),
                ('AssessmentItem2', models.CharField(max_length=40)),
                ('AssessmentItem2DueDate', models.DateField()),
                ('AssessmentItem3', models.CharField(max_length=40)),
                ('AssessmentItem3DueDate', models.DateField()),
                ('ContentDescription', models.CharField(max_length=5000)),
            ],
        ),
    ]
