# Generated by Django 6.0.2 on 2026-05-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_unitoutline'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitoutline',
            name='DeliveredAsVET',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
